name: hop

on: workflow_dispatch

permissions:
  actions: write

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X DELETE -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/ItzhakAvm/cache/actions/caches/8
      # - uses: actions/github-script@v7
      #   env:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     script: |
      #       core.exportVariable('ACTIONS_CACHE_URL', process.env['ACTIONS_CACHE_URL'])
      #       core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN'])
      #       core.exportVariable('ACTIONS_RUNTIME_URL', process.env['ACTIONS_RUNTIME_URL'])
      # - run: echo "hophophop" > prime-numbers
      # # - run: |
      # #     curl -v -XPATCH -H "Authorization: Bearer ${ACTIONS_RUNTIME_TOKEN}" -H "User-Agent: actions/cache" -H "Accept: application/json;api-version=6.0-preview.1" \
      # #     -H "Content-Type: application/octet-stream" -H "Content-Range: bytes 0-9/10" --upload-file prime-numbers \
      # #     "${ACTIONS_CACHE_URL}_apis/artifactcache/caches/8"
      # - run: |
      #     curl -v -XDELETE -H "Authorization: Bearer ${ACTIONS_RUNTIME_TOKEN}" -H "User-Agent: actions/cache" -H "Accept: application/json;api-version=6.0-preview.1" \
      #     "${ACTIONS_CACHE_URL}_apis/artifactcache/caches/8"
