name: hop

on: workflow_dispatch

permissions: {}

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - run: echo "" > prime-numbers
      - run: |
          curl -i -XPATCH -H "Authorization: Bearer ${ACTIONS_RUNTIME_TOKEN}" -H "User-Agent: actions/cache" -H "Accept: application/json;api-version=6.0-preview.1" \
          "Content-Type: application/octet-stream" --data-binary @prime-numbers \
          "${ACTIONS_CACHE_URL}_apis/artifactcache/caches/8"
