name: workflow_dispatch

on: workflow_dispatch

permissions: {}

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v3
        id: restore-cache
        with:
          path: prime-numbers
          key: ${{ runner.os }}-primes
      - name: Print Prime Numbers
        if: steps.cache.outputs.cache-hit == 'true'
        run: cat prime-numbers
      - name: Generate Prime Numbers
        run: echo "workflow_dispatch-${{ github.run_id }}" > prime-numbers
      - uses: actions/cache/save@v3
        with:
          path: prime-numbers
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}
