name: workflow_run

on:
  workflow_run:
    workflows: [pull_request]
    types:
      - completed

permissions: {}

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Primes
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            prime-numbers
            prime-numbers1
          key: ${{ runner.os }}-primes
      - name: Print Prime Numbers
        if: steps.cache.outputs.cache-hit == 'true'
        run: cat prime-numbers
      - name: Generate Prime Numbers
        run: |
          echo "workflow_run" > prime-numbers
          echo "workflow_run_1" > prime-numbers1
